<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
        <Folder Include="Models\Interfaces\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.11"/>
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.11" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.11"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.11"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.11"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.11">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1"/>
        <PackageReference Include="FreeSpire.XLS" Version="16.4.0" />
        <PackageReference Include="MessageBox.Avalonia" Version="3.3.1.1" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
        <PackageReference Include="MySqlConnector" Version="2.5.0" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Views\EditViews\BonusEditWindow.axaml.cs">
        <DependentUpon>BonusEditWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\EditViews\EmployeeEditWindow.axaml.cs">
        <DependentUpon>EmployeeEditWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\EditViews\EmployeeTaskEditWindow.axaml.cs">
        <DependentUpon>EmployeeTaskEditWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\EditViews\PositionEditWindow.axaml.cs">
        <DependentUpon>PositionEditWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\MainViews\EmployeeTaskView.axaml.cs">
        <DependentUpon>EmployeeTaskView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\MainViews\BonusView.axaml.cs">
        <DependentUpon>BonusView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\MainViews\EmployeeView.axaml.cs">
        <DependentUpon>EmployeeView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\MainViews\PositionView.axaml.cs">
        <DependentUpon>PositionView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\MainViews\SalaryView.axaml.cs">
        <DependentUpon>SalaryView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\MainViews\SettingsView.axaml.cs">
        <DependentUpon>SettingsView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\AuxiliaryViews\EmployeeSelectorWindow.axaml.cs">
        <DependentUpon>EmployeeSelectorWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\AuxiliaryViews\PositionSelectorWindow.axaml.cs">
        <DependentUpon>PositionSelectorWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>
</Project>
